export { default as Slider } from './Slider/Slider'
export { default as MiniSlider } from './Slider/MiniSlider'
export { default as Category } from './CategoryCourse/Category'
export { default as SocialNetworks } from './SocialNetworks/SocialNetworks'
export { default as Weblogs } from './Weblog/Weblogs'
export { default as Courses } from './Courses/Courses'
export { default as Download } from './Download/Download'